### ISSUE TITLE
About training with data generation on the fly.

### ISSUE THREAD

**Issue by Guptajakala** [PruneTruong/GLU-Net#3]
Hi, thanks for the great work!
Did you observe any test-time performance difference by training with 1) creating synthetic training and evaluation pairs on the fly (data might be different in each epoch) and 2) save them to disk and load them during training (data are mostly same in each epoch) ?

**Comment by PruneTruong** [comment]
Hi, I only did very few preliminary experiments with creating data on the fly and changing the transformations at each epoch. This is because I mostly used the same settings than DGC-Net to be directly comparable, and they apply the same transformations at each epoch during training, without any further augmentation. Besides, creating the image pairs and the flow on the fly is slow, particular the warping operations. But, if you perform experiments on this subject, please let me know your results !

**Comment by Guptajakala** [comment]
Thanks for the info! I will let you know after I try it.
