### ISSUE TITLE
Generating CSV file for custom data

### ISSUE THREAD

**Issue by Pari-singh** [PruneTruong/GLU-Net#4]
Hi @martin-danelljan @PruneTruong 

Thanks for the great repository. I am trying to train the GLUNet model for my custom data (training on KITTI) and so wanted to know how to generate the CSV file for any data other than DPED+CS+ADE. Would really appreciate if you could share some information on different columns and picking/finding values for them. 

Thanks in advance.

**Comment by PruneTruong** [comment]
Hi, for the creation of the csv file, in this repo, I wanted GLU-Net to be directly comparable to DGC-Net. I therefore used the geometric transformations parameters that they provided (in an equivalent csv file), and I only changed the column corresponding to the image list on which I wanted to apply the transformations ( I couldn't used the same images than DGC-Net because they are of too small resolution). The other columns represent which type of transformation to apply (affine, tps or homography) and the corresponding parameters of the transformation (for example, the parameters of the homography matrix).  

If you want to use the same transformations on different images, you just need to change the column corresponding to the image list. If you want different transformation parameters, you need to generate those yourself (for example, generating random homographies) and then generate a new csv file containing the updated information. 
Hope that helps !
